-- Bootstraps the shared onemep_dev schema for integration tests. The feature service does not
-- own user_master (the identity service does), but its project lead/member FKs reference it, so a
-- minimal, seeded copy must exist before Flyway applies the feature migrations.
CREATE SCHEMA IF NOT EXISTS onemep_dev;
SET search_path TO onemep_dev;

CREATE TABLE user_master (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active_status  BOOLEAN,
    email          VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    password       VARCHAR(255),
    last_login     TIMESTAMP
);

INSERT INTO user_master (id, active_status, email, first_name, last_name) VALUES
    (1, true, 'lead1@onemep.com',   'Ava',  'Lead'),
    (2, true, 'member2@onemep.com', 'Ben',  'Member'),
    (3, true, 'lead3@onemep.com',   'Cara', 'Lead');
