-- ============================================================================
-- V15 - DID Specifications (Technical Master "DID" tab).
--
-- Supersedes the provisional project_did_specification shape (line items) with the
-- real Design Intent & Brief record now that the story is detailed. Adds the four
-- remaining DID subsections:
--   * Delivery Schedule       — repurposes project_delivery_schedule (ONEMEP-15),
--                                tagged is_did_stage so DID save/delete never touches
--                                unrelated general milestone rows.
--   * Client Information      — project_did_client_info + project_did_contact
--   * Architect Team          — project_did_architect_team + project_did_contact
--   * Structure Consultant Team — project_did_structure_consultant_team + project_did_contact
--
-- Default rows (delivery stages, client contact designations) are NOT seeded here —
-- they're configured in application.yml and synthesized on GET when nothing is saved
-- yet, so a project's data isn't polluted just by opening the DID tab.
-- ============================================================================

-- ── Design Intent & Brief (redesign; was a provisional line-item table) ─────
DROP TABLE IF EXISTS project_did_specification;

CREATE TABLE project_did_specification (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id         BIGINT        NOT NULL,
    locked_design_intent        VARCHAR(2000) NOT NULL,
    initial_client_rfi_response VARCHAR(2000),
    green_rating_target         VARCHAR(50),
    sustainability_mandates     VARCHAR(2000),
    created_date                TIMESTAMP     NOT NULL,
    created_by                  BIGINT,
    updated_by                  BIGINT,
    updated_date                TIMESTAMP,
    CONSTRAINT fk_did_spec_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT uq_did_spec_master UNIQUE (technical_master_id)
);

-- ── Green rating target — configured options, not a hardcoded enum ─────────
CREATE TABLE did_green_rating_option (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL,
    label         VARCHAR(100) NOT NULL,
    option_order  INT          NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_green_rating_option_code UNIQUE (code)
);

INSERT INTO did_green_rating_option (code, label, option_order, active) VALUES
    ('NONE', 'None', 1, TRUE),
    ('IGBC', 'IGBC', 2, TRUE),
    ('GRIHA', 'GRIHA', 3, TRUE),
    ('LEED', 'LEED', 4, TRUE);

-- ── Delivery Schedule — repurpose project_delivery_schedule (ONEMEP-15) ─────
-- milestone doubles as the DID "stage name"; planned_date/actual_date/deliverable/status
-- stay untouched for general (non-DID) rows. is_did_stage scopes DID's diff/delete so it
-- can never affect rows created through the generic /delivery-schedule endpoints.
ALTER TABLE project_delivery_schedule
    ADD COLUMN start_date    DATE,
    ADD COLUMN end_date      DATE,
    ADD COLUMN is_did_stage  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN stage_order   INT;

ALTER TABLE project_delivery_schedule
    ADD CONSTRAINT ck_delivery_did_dates
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date);

CREATE INDEX idx_delivery_project_did_stage
    ON project_delivery_schedule (project_id, is_did_stage);

-- ── Client Information ──────────────────────────────────────────────────────
CREATE TABLE project_did_client_info (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id  BIGINT       NOT NULL,
    client_name          VARCHAR(200),
    client_company       VARCHAR(200),
    created_date         TIMESTAMP    NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    updated_date         TIMESTAMP,
    CONSTRAINT fk_did_client_info_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT uq_did_client_info_master UNIQUE (technical_master_id)
);

-- ── Architect Team ───────────────────────────────────────────────────────────
CREATE TABLE project_did_architect_team (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id  BIGINT       NOT NULL,
    architecture_firm    VARCHAR(200),
    created_date         TIMESTAMP    NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    updated_date         TIMESTAMP,
    CONSTRAINT fk_did_architect_team_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT uq_did_architect_team_master UNIQUE (technical_master_id)
);

-- ── Structure Consultant Team ───────────────────────────────────────────────
CREATE TABLE project_did_structure_consultant_team (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id    BIGINT       NOT NULL,
    structural_consultancy VARCHAR(200),
    created_date           TIMESTAMP    NOT NULL,
    created_by             BIGINT,
    updated_by             BIGINT,
    updated_date           TIMESTAMP,
    CONSTRAINT fk_did_structure_team_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT uq_did_structure_team_master UNIQUE (technical_master_id)
);

-- ── Contacts — shared row shape across Client / Architect / Structure ──────
CREATE TABLE project_did_contact (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id  BIGINT       NOT NULL,
    party_type           VARCHAR(20)  NOT NULL,
    designation          VARCHAR(100),
    name                 VARCHAR(100),
    mail_id              VARCHAR(150),
    contact_no           VARCHAR(30),
    is_default_row       BOOLEAN      NOT NULL DEFAULT FALSE,
    contact_order        INT          NOT NULL DEFAULT 0,
    created_date         TIMESTAMP    NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    updated_date         TIMESTAMP,
    CONSTRAINT fk_did_contact_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT ck_did_contact_party_type CHECK (party_type IN ('CLIENT', 'ARCHITECT', 'STRUCTURE'))
);
CREATE INDEX idx_did_contact_master_party ON project_did_contact (technical_master_id, party_type);
