-- ============================================================================
-- V16 - Generic reference-data catalogue (Sprint 3 prerequisite).
--
-- Sprint 3 (ONEMEP-32..44) resolves Discipline, Type, Subject, Floor and Stage
-- from "the authoritative Master Data". None of those existed. Rather than five
-- near-identical code/label tables, they share one catalogue keyed by
-- lookup_type -- the shape did_green_rating_option (V15) already established.
--
-- Referential integrity is NOT sacrificed for that convenience: uq_lookup_id_type
-- lets each consumer declare a composite FK pinned to a single lookup_type, so
-- the database physically rejects (say) a FLOOR id in a discipline column.
-- See V17 for the first consumer.
--
-- Scope rule: simple code/label catalogues belong here. Masters carrying their
-- own behaviour or relationships keep their own table (unit_master has
-- accepted_input_type, team_role_master belongs to a tier, technical_master owns
-- fields and sections). did_green_rating_option stays where it is -- migrating
-- working data purely for tidiness is not worth the risk.
-- ============================================================================

CREATE TABLE lookup_value (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lookup_type   VARCHAR(40)  NOT NULL,
    code          VARCHAR(20)  NOT NULL,
    label         VARCHAR(150) NOT NULL,
    sort_order    INT          NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    -- One code per catalogue. Codes are compared case-insensitively by the
    -- service; stored upper-case by convention.
    CONSTRAINT uq_lookup_type_code UNIQUE (lookup_type, code),

    -- Looks redundant against the PK, and is not: a composite FK can only
    -- target a uniquely-constrained column pair. This is what lets a consumer
    -- pin its reference to one lookup_type.
    CONSTRAINT uq_lookup_id_type UNIQUE (id, lookup_type),

    CONSTRAINT ck_lookup_type CHECK (lookup_type IN
        ('DISCIPLINE', 'DESIGN_TYPE', 'SUBJECT', 'FLOOR', 'ZONE', 'STAGE'))
);

CREATE INDEX idx_lookup_type_active ON lookup_value (lookup_type, is_active);

-- ── Seeds ───────────────────────────────────────────────────────────────────
-- PROVISIONAL. Only the codes visible in the ONEMEP-33/35/36 acceptance criteria
-- and the V14 stage comment are seeded here. ONEMEP-33 states outright that the
-- full catalogue "should be attached to this story or referenced from the
-- relevant Master Data specification so QA can validate every available dropdown
-- value" -- that list has not been supplied. Extend via a follow-up migration
-- once the business confirms; do not edit this file after it has been applied.
--
-- 'XX' is deliberately absent: ONEMEP-36 generates it as the placeholder for an
-- empty Design Number segment, so it is produced, never selected.

INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date) VALUES
    -- Discipline (ONEMEP-33 confirms M and PHE; ONEMEP-36 references E)
    ('DISCIPLINE',  'M',   'Mechanical / HVAC',        1, TRUE, NOW()),
    ('DISCIPLINE',  'E',   'Electrical',               2, TRUE, NOW()),
    ('DISCIPLINE',  'PHE', 'Public Health / Plumbing', 3, TRUE, NOW()),

    -- Design/document type (ONEMEP-33 confirms PLN and SCH)
    ('DESIGN_TYPE', 'PLN', 'Plan / Layout',            1, TRUE, NOW()),
    ('DESIGN_TYPE', 'SCH', 'Schematic',                2, TRUE, NOW()),

    -- Subject (ONEMEP-33 confirms CHW only)
    ('SUBJECT',     'CHW', 'Chilled Water',            1, TRUE, NOW()),

    -- Stage (V14 comment: CON / SD / DD / TS / GFC / AB -- an ordered progression,
    -- which is why sort_order matters rather than being cosmetic)
    ('STAGE',       'CON', 'Concept',                  1, TRUE, NOW()),
    ('STAGE',       'SD',  'Schematic Design',         2, TRUE, NOW()),
    ('STAGE',       'DD',  'Detailed Design',          3, TRUE, NOW()),
    ('STAGE',       'TS',  'Tender Set',               4, TRUE, NOW()),
    ('STAGE',       'GFC', 'Good For Construction',    5, TRUE, NOW()),
    ('STAGE',       'AB',  'As Built',                 6, TRUE, NOW());

-- FLOOR and ZONE are intentionally unseeded. ONEMEP-36 shows both 'L01' and '00'
-- as floor codes without defining the scheme, and describes Zone as manually
-- entered ("Where Zone is entered manually...") rather than selected -- so
-- whether ZONE is a catalogue at all is still an open question for the business.
