-- ============================================================================
-- V17 - Checklist Master (ONEMEP-32/33/34).
--
-- One master record is either a multi-item CHECKLIST (named, 1-30 items) or a
-- SINGLE_ITEM (unnamed, exactly one item). The type is fixed at creation:
-- ONEMEP-34 requires the backend to reject a type change independently of the
-- UI, so the rule is expressed in the schema as well as the service.
--
-- Applicability is the load-bearing part. Each record declares which Designs it
-- applies to across three segments, with OR within a segment and AND across
-- segments, and a wildcard "Any" per segment. That combination is what the
-- approval flow (ONEMEP-40) resolves a Design's checklist from.
-- ============================================================================

CREATE TABLE checklist_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_type   VARCHAR(20)  NOT NULL,
    name          VARCHAR(50),
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    version       INT          NOT NULL DEFAULT 0,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT ck_checklist_record_type CHECK (record_type IN ('CHECKLIST', 'SINGLE_ITEM')),

    -- A Checklist is named; a Single Item never is. ONEMEP-33: "Checklist Name
    -- shall not be required in Single Item mode"; ONEMEP-34: "Checklist Name
    -- shall not be required or accepted for Single Item records."
    CONSTRAINT ck_checklist_name_by_type CHECK (
        (record_type = 'CHECKLIST' AND name IS NOT NULL)
        OR (record_type = 'SINGLE_ITEM' AND name IS NULL))
);

-- ONEMEP-33: "The checklist name should be unique." Scope was never stated, so
-- this assumes global and case-insensitive across named records. Single Items
-- carry no name and are therefore unconstrained. Narrow this to a per-
-- applicability scope if the business says otherwise.
CREATE UNIQUE INDEX uq_checklist_name
    ON checklist_master (LOWER(name)) WHERE name IS NOT NULL;

CREATE INDEX idx_checklist_active ON checklist_master (is_active);

-- ── Items ───────────────────────────────────────────────────────────────────
-- Ordered, 1-30 for a Checklist and exactly 1 for a Single Item. Those counts
-- are service-enforced; the schema guarantees ordering is unambiguous.
CREATE TABLE checklist_item (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id  BIGINT       NOT NULL,
    sort_order    INT          NOT NULL,
    text          VARCHAR(250) NOT NULL,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_checklist_item_master FOREIGN KEY (checklist_id)
        REFERENCES checklist_master (id) ON DELETE CASCADE,
    CONSTRAINT uq_checklist_item_order UNIQUE (checklist_id, sort_order)
);

CREATE INDEX idx_checklist_item_master ON checklist_item (checklist_id);

-- ── Applicability ───────────────────────────────────────────────────────────
-- One row per selected value. value_id NULL means "Any" for that segment.
--
-- First real consumer of the V16 composite-FK pattern: segment doubles as the
-- type pin, because the three segment names are exactly the lookup_type names
-- they reference. A DISCIPLINE row therefore cannot point at a SUBJECT value —
-- the database rejects it, not merely the service.
CREATE TABLE checklist_applicability (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checklist_id  BIGINT      NOT NULL,
    segment       VARCHAR(40) NOT NULL,
    value_id      BIGINT,
    value_type    VARCHAR(40),
    created_date  TIMESTAMP   NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT ck_checklist_segment CHECK (segment IN ('DISCIPLINE', 'DESIGN_TYPE', 'SUBJECT')),

    -- Either a wildcard (both columns null) or a real value whose type is the
    -- segment itself. Nothing else is representable.
    CONSTRAINT ck_checklist_applicability_pair CHECK (
        (value_id IS NULL AND value_type IS NULL)
        OR (value_id IS NOT NULL AND value_type = segment)),

    CONSTRAINT fk_checklist_applicability_master FOREIGN KEY (checklist_id)
        REFERENCES checklist_master (id) ON DELETE CASCADE,

    CONSTRAINT fk_checklist_applicability_value FOREIGN KEY (value_id, value_type)
        REFERENCES lookup_value (id, lookup_type)
);

-- At most one wildcard per segment.
CREATE UNIQUE INDEX uq_checklist_applicability_any
    ON checklist_applicability (checklist_id, segment) WHERE value_id IS NULL;

-- A specific value may not be selected twice in the same segment.
CREATE UNIQUE INDEX uq_checklist_applicability_value
    ON checklist_applicability (checklist_id, segment, value_id) WHERE value_id IS NOT NULL;

CREATE INDEX idx_checklist_applicability_master ON checklist_applicability (checklist_id);
CREATE INDEX idx_checklist_applicability_lookup ON checklist_applicability (segment, value_id);

-- NOTE: "Any and a specific value cannot coexist in one segment" is not
-- expressible as a table constraint and is enforced in the service layer, with
-- a regression test covering it.
