-- ============================================================================
-- V18 - Design Register (ONEMEP-35 listing, ONEMEP-36 add, ONEMEP-37 edit).
--
-- A Design belongs to exactly one Project and carries a generated Design Number
-- built from its segments:
--     ONEMEP-<ProjectCode>-<Zone>-<Disc>-<Type>-<Subject>-<Floor>-<Stage>
--
-- Two decisions worth stating, both taken from the tickets' worked examples
-- because the acceptance criteria contradict themselves (see the Sprint 3
-- teardown, Q1 and Q2):
--
--  * Zone is optional and falls back to the literal 'XX'. Every example in
--    ONEMEP-36/37/38 shows 'XX' in the zone position, and ONEMEP-36 describes
--    Zone as typed rather than selected — so it is a plain code column, not a
--    catalogue reference. The other five segments are mandatory.
--
--  * A Design Number is NOT unique on its own. ONEMEP-36 states outright that
--    two Designs may share one when their Titles differ, and gives a worked
--    example. Uniqueness is therefore the full segment set plus the normalised
--    Title. ONEMEP-35's import wording implies the narrower rule; that ticket
--    must be reconciled against this one before the importer is built.
--
-- Each catalogue reference uses the V16 composite-FK pattern: a *_type column
-- defaulted and CHECK-pinned to one lookup_type, so a Subject id can never be
-- stored in the discipline column. The *_type columns are unmapped in JPA —
-- the defaults fill them and Hibernate never writes them.
-- ============================================================================

CREATE TABLE design (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id       BIGINT       NOT NULL,

    -- ── Design Number segments; immutable after creation (ONEMEP-37) ────────
    zone_code        VARCHAR(10)  NOT NULL DEFAULT 'XX',

    discipline_id    BIGINT       NOT NULL,
    discipline_type  VARCHAR(40)  NOT NULL DEFAULT 'DISCIPLINE',
    type_id          BIGINT       NOT NULL,
    type_type        VARCHAR(40)  NOT NULL DEFAULT 'DESIGN_TYPE',
    subject_id       BIGINT       NOT NULL,
    subject_type     VARCHAR(40)  NOT NULL DEFAULT 'SUBJECT',
    floor_id         BIGINT       NOT NULL,
    floor_type       VARCHAR(40)  NOT NULL DEFAULT 'FLOOR',
    stage_id         BIGINT       NOT NULL,
    stage_type       VARCHAR(40)  NOT NULL DEFAULT 'STAGE',

    design_number    VARCHAR(120) NOT NULL,

    -- ── Editable information ───────────────────────────────────────────────
    title            VARCHAR(200) NOT NULL,
    title_normalized VARCHAR(200) NOT NULL,
    sheet_size       VARCHAR(10),
    scale            VARCHAR(30),
    prepared_by      VARCHAR(150),

    work_progress    VARCHAR(30)  NOT NULL DEFAULT 'NOT_STARTED',
    status           VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',

    version          INT          NOT NULL DEFAULT 0,
    created_date     TIMESTAMP    NOT NULL,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP,

    CONSTRAINT fk_design_project FOREIGN KEY (project_id) REFERENCES project_master (id),

    CONSTRAINT ck_design_discipline_type CHECK (discipline_type = 'DISCIPLINE'),
    CONSTRAINT ck_design_type_type       CHECK (type_type = 'DESIGN_TYPE'),
    CONSTRAINT ck_design_subject_type    CHECK (subject_type = 'SUBJECT'),
    CONSTRAINT ck_design_floor_type      CHECK (floor_type = 'FLOOR'),
    CONSTRAINT ck_design_stage_type      CHECK (stage_type = 'STAGE'),

    CONSTRAINT fk_design_discipline FOREIGN KEY (discipline_id, discipline_type)
        REFERENCES lookup_value (id, lookup_type),
    CONSTRAINT fk_design_type FOREIGN KEY (type_id, type_type)
        REFERENCES lookup_value (id, lookup_type),
    CONSTRAINT fk_design_subject FOREIGN KEY (subject_id, subject_type)
        REFERENCES lookup_value (id, lookup_type),
    CONSTRAINT fk_design_floor FOREIGN KEY (floor_id, floor_type)
        REFERENCES lookup_value (id, lookup_type),
    CONSTRAINT fk_design_stage FOREIGN KEY (stage_id, stage_type)
        REFERENCES lookup_value (id, lookup_type),

    CONSTRAINT ck_design_work_progress CHECK (work_progress IN
        ('NOT_STARTED', 'IN_PROGRESS', 'ISSUED', 'COMPLETED')),

    -- Workflow states from ONEMEP-38; driven by the approval flow (ONEMEP-40),
    -- never set directly from the Design screens.
    CONSTRAINT ck_design_status CHECK (status IN
        ('DRAFT', 'IN_PROGRESS', 'UNDER_REVIEW', 'EDIT_REQUESTED', 'REJECTED', 'APPROVED')),

    -- The duplicate rule, in the database rather than only in the service —
    -- ONEMEP-36: "Duplicate validation shall also be enforced by the backend."
    CONSTRAINT uq_design_identity UNIQUE (
        project_id, zone_code, discipline_id, type_id, subject_id, floor_id, stage_id,
        title_normalized)
);

CREATE INDEX idx_design_project        ON design (project_id);
CREATE INDEX idx_design_number         ON design (design_number);
CREATE INDEX idx_design_project_disc   ON design (project_id, discipline_id);
CREATE INDEX idx_design_project_stage  ON design (project_id, stage_id);
CREATE INDEX idx_design_updated        ON design (project_id, updated_date DESC);

-- ── Floor seeds ─────────────────────────────────────────────────────────────
-- PROVISIONAL, and only what the tickets actually show: ONEMEP-36 uses 'L01'
-- and ONEMEP-37/38 use '00'. No floor scheme has been supplied, so nothing is
-- invented here — a Design cannot be created against a floor that does not
-- exist, which is the correct failure until the business provides the list.
INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date) VALUES
    ('FLOOR', '00',  'Ground Floor', 1, TRUE, NOW()),
    ('FLOOR', 'L01', 'Level 01',     2, TRUE, NOW());
