-- ============================================================================
-- V19 - Design Activity audit trail (ONEMEP-43).
--
-- Append-only history of what happened to a Design. Mirrors the shape
-- project_activity_log (V2) already established, with two additions the ticket
-- requires:
--
--  * actor_label snapshots who acted, at the moment they acted. ONEMEP-43:
--    "Historic Activity shall still display that user's recorded identity. Do
--    not display 'Unknown User' where the historic identity is available."
--    Resolving names at read time would fail once a user is removed from the
--    identity service, and would put a gRPC call on the audit write path.
--
--  * detail is denormalised prose, never a foreign key to the thing it
--    describes. That is what lets "Uploaded 'riser.pdf'" survive the file
--    being deleted, which ONEMEP-43 demands.
--
-- Rows are never updated or deleted by the application. The only cascade is
-- from the Design itself: a Design's trail is meaningless without the Design,
-- and no screen can reach it once the Design is gone.
-- ============================================================================

CREATE TABLE design_activity_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id     BIGINT        NOT NULL,

    -- Stable machine code; the UI never shows this.
    action        VARCHAR(50)   NOT NULL,

    -- Business-friendly sentence, e.g. "Title changed from 'A' to 'B'".
    detail        VARCHAR(1000) NOT NULL,

    -- Display name captured at write time. NULL means the platform acted;
    -- the read model renders that as "System".
    actor_label   VARCHAR(150),

    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_design_activity_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE
);

-- The listing is always "this Design, newest first". id breaks ties so two
-- events written in the same millisecond still order deterministically
-- (ONEMEP-43: "Ordering for identical timestamps shall use the persisted event
-- sequence/identifier so the UI remains deterministic").
CREATE INDEX idx_design_activity_design ON design_activity_log (design_id, created_date DESC, id DESC);
