-- ============================================================================
-- V1 - ONE-MEP Feature Service base schema (Projects + Master Data)
--
-- Bounded context: Project & Master Data (Jira epics ONEMEP-11, ONEMEP-25).
-- Tables live in the shared onemep_dev schema but are owned by this service;
-- Flyway tracks them in its own history table (flyway_feature_history) so the
-- identity service's migration timeline is never touched.
--
-- Every table carries the shared BaseEntity audit columns:
--   id, created_date, created_by, updated_by, updated_date
-- ============================================================================

-- ── Master Data: Tier (ONEMEP-16/17/18) ────────────────────────────────────
-- Groups team roles in the member picker. Inactive tiers are hidden from the picker.
CREATE TABLE tier_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_tier_name UNIQUE (name)
);

-- ── Master Data: Team Role (ONEMEP-19/20/21) ───────────────────────────────
-- Assigned to project members; each role is grouped under exactly one tier.
CREATE TABLE team_role_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    tier_id       BIGINT       NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_team_role_name UNIQUE (name),
    CONSTRAINT fk_team_role_tier FOREIGN KEY (tier_id) REFERENCES tier_master (id)
);
CREATE INDEX idx_team_role_tier ON team_role_master (tier_id);

-- ── Master Data: Category (ONEMEP-22/23/24) ─────────────────────────────────
-- Classifies projects. The prefix drives project-number generation and is LOCKED
-- after creation (enforced in the service layer; DB guarantees uniqueness).
CREATE TABLE category_master (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_number  VARCHAR(50)  NOT NULL,
    name             VARCHAR(150) NOT NULL,
    prefix           VARCHAR(10)  NOT NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date     TIMESTAMP    NOT NULL,
    created_by       BIGINT,
    updated_by       BIGINT,
    updated_date     TIMESTAMP,
    CONSTRAINT uq_category_number UNIQUE (category_number),
    CONSTRAINT uq_category_name   UNIQUE (name),
    CONSTRAINT uq_category_prefix UNIQUE (prefix),
    CONSTRAINT ck_category_prefix_format CHECK (prefix = UPPER(prefix) AND char_length(prefix) BETWEEN 1 AND 10)
);

-- ── Master Data: Unit (ONEMEP-26/27/28) ─────────────────────────────────────
-- Measurement types used to validate Technical Master fields.
CREATE TABLE unit_master (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(150) NOT NULL,
    symbol               VARCHAR(30)  NOT NULL,
    accepted_input_type  VARCHAR(20)  NOT NULL,
    is_active            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date         TIMESTAMP    NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    updated_date         TIMESTAMP,
    CONSTRAINT uq_unit_symbol UNIQUE (symbol),
    CONSTRAINT ck_unit_input_type CHECK (accepted_input_type IN ('INTEGER', 'DECIMAL', 'TEXT', 'BOOLEAN'))
);

-- ── Project (ONEMEP-12/13/14/15) ─────────────────────────────────────────────
-- project_number is system-generated from the category prefix and LOCKED; category
-- is also protected after creation (both enforced in the service layer).
CREATE TABLE project_master (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_number    VARCHAR(50)  NOT NULL,
    name              VARCHAR(200) NOT NULL,
    category_id       BIGINT       NOT NULL,
    lifecycle_status  VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',
    priority          VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    description       TEXT,
    is_active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date      TIMESTAMP    NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    updated_date      TIMESTAMP,
    CONSTRAINT uq_project_number UNIQUE (project_number),
    CONSTRAINT fk_project_category FOREIGN KEY (category_id) REFERENCES category_master (id),
    CONSTRAINT ck_project_lifecycle CHECK (lifecycle_status IN
        ('DRAFT', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', 'ARCHIVED')),
    CONSTRAINT ck_project_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);
CREATE INDEX idx_project_category ON project_master (category_id);

-- ── Project ↔ Leads (many-to-many; a project can have multiple leads) ─────────
-- References onemep_dev.user_master, owned by the identity service.
CREATE TABLE project_lead_mapping (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT    NOT NULL,
    user_id       BIGINT    NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_project_lead UNIQUE (project_id, user_id),
    CONSTRAINT fk_project_lead_project FOREIGN KEY (project_id) REFERENCES project_master (id),
    CONSTRAINT fk_project_lead_user    FOREIGN KEY (user_id)    REFERENCES user_master (id)
);
CREATE INDEX idx_project_lead_project ON project_lead_mapping (project_id);
CREATE INDEX idx_project_lead_user    ON project_lead_mapping (user_id);

-- ── Project ↔ Members (member assigned a team role on a project) ──────────────
CREATE TABLE project_member_mapping (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT    NOT NULL,
    user_id       BIGINT    NOT NULL,
    team_role_id  BIGINT    NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_project_member UNIQUE (project_id, user_id, team_role_id),
    CONSTRAINT fk_project_member_project FOREIGN KEY (project_id)   REFERENCES project_master (id),
    CONSTRAINT fk_project_member_user    FOREIGN KEY (user_id)      REFERENCES user_master (id),
    CONSTRAINT fk_project_member_role    FOREIGN KEY (team_role_id) REFERENCES team_role_master (id)
);
CREATE INDEX idx_project_member_project ON project_member_mapping (project_id);
CREATE INDEX idx_project_member_user    ON project_member_mapping (user_id);
CREATE INDEX idx_project_member_role    ON project_member_mapping (team_role_id);

-- ── Technical Master (ONEMEP-29) ─────────────────────────────────────────────
-- PROVISIONAL: the story has no description yet. Modeled as a named technical field
-- whose measurement type is validated by a Unit. Revisit once ONEMEP-29 is detailed.
CREATE TABLE technical_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    unit_id       BIGINT,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_technical_master_name UNIQUE (name),
    CONSTRAINT fk_technical_master_unit FOREIGN KEY (unit_id) REFERENCES unit_master (id)
);
CREATE INDEX idx_technical_master_unit ON technical_master (unit_id);
