-- ============================================================================
-- V20 - Design task details (ONEMEP-38).
--
-- "The Design itself shall operate as a project task", so these live on the
-- design row rather than in a side table — one row, one lifecycle, no join for
-- the Detail screen.
--
-- Duration is deliberately absent. ONEMEP-38 derives it from the two dates and
-- forbids editing it; storing it would create a third value that can disagree
-- with the two it comes from.
--
-- Status is also absent here — it already exists on design (V18) and is owned
-- by the approval flow. ONEMEP-38 shows it in the Task section but explicitly
-- forbids setting it there.
-- ============================================================================

ALTER TABLE design
    ADD COLUMN owner_id       BIGINT,
    ADD COLUMN priority       VARCHAR(10)  NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN completion_pct INT          NOT NULL DEFAULT 0,
    ADD COLUMN start_date     DATE,
    ADD COLUMN due_date       DATE,
    ADD COLUMN reminder       VARCHAR(30)  NOT NULL DEFAULT 'NONE',
    ADD COLUMN source         VARCHAR(20)  NOT NULL DEFAULT 'MANUAL';

ALTER TABLE design
    -- user_master is owned by the identity service but shares this schema, so the
    -- reference is a real foreign key rather than a loose id.
    ADD CONSTRAINT fk_design_owner FOREIGN KEY (owner_id) REFERENCES user_master (id),

    ADD CONSTRAINT ck_design_priority CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),

    -- ONEMEP-38: "Valid values shall be: 0 to 100 inclusive".
    ADD CONSTRAINT ck_design_completion CHECK (completion_pct BETWEEN 0 AND 100),

    ADD CONSTRAINT ck_design_reminder CHECK (reminder IN
        ('NONE', 'ON_DUE_DATE', 'ONE_DAY_BEFORE', 'THREE_DAYS_BEFORE', 'ONE_WEEK_BEFORE')),

    -- MANUAL for a Design added through Add Drawing; IMPORT for one created by the
    -- spreadsheet importer (ONEMEP-35, slice 8).
    ADD CONSTRAINT ck_design_source CHECK (source IN ('MANUAL', 'IMPORT')),

    -- ONEMEP-38: "The Due Date shall not be earlier than the Start Date." Equal dates
    -- are permitted. Either being absent is fine — the Design may not be scheduled yet.
    ADD CONSTRAINT ck_design_dates CHECK (
        start_date IS NULL OR due_date IS NULL OR due_date >= start_date);

CREATE INDEX idx_design_owner ON design (owner_id);

-- ── Tags ────────────────────────────────────────────────────────────────────
-- label_normalized backs the case-insensitive duplicate rule ONEMEP-38 asks for
-- ("Plant Room" and "plant room" are the same tag), while label preserves what
-- the user actually typed for display.
CREATE TABLE design_tag (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id         BIGINT      NOT NULL,
    label             VARCHAR(50) NOT NULL,
    label_normalized  VARCHAR(50) NOT NULL,
    created_date      TIMESTAMP   NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    updated_date      TIMESTAMP,

    CONSTRAINT fk_design_tag_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE,
    CONSTRAINT uq_design_tag UNIQUE (design_id, label_normalized)
);

CREATE INDEX idx_design_tag_design ON design_tag (design_id);
