-- ============================================================================
-- V21 - Uploaded files and version history (ONEMEP-39).
--
-- Two levels, and the distinction is the whole ticket: a *logical file* is one
-- row in the Uploaded Files table no matter how many revisions it has, and each
-- revision is an immutable row beneath it. Uploading R1 must not create a
-- second top-level entry, and must not disturb R0.
--
-- Bytes live in object storage (see FileStorage); only metadata and the storage
-- key are held here. Nothing in this schema stores file content.
-- ============================================================================

CREATE TABLE design_file (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id                BIGINT       NOT NULL,

    -- What the Uploaded Files table shows. Derived from the first upload's
    -- filename; the extension is carried per version, since a later revision may
    -- legitimately arrive as a different format.
    display_name             VARCHAR(255) NOT NULL,
    display_name_normalized  VARCHAR(255) NOT NULL,

    -- Points at whichever revision is Current. Nullable only for the instant
    -- between inserting the file and its first version.
    current_version_id       BIGINT,

    -- Allocator for the next revision number. Incremented under a row lock so two
    -- simultaneous uploads cannot be handed the same R-number, which ONEMEP-39
    -- calls out explicitly.
    next_revision_no         INT          NOT NULL DEFAULT 0,

    created_date             TIMESTAMP    NOT NULL,
    created_by               BIGINT,
    updated_by               BIGINT,
    updated_date             TIMESTAMP,

    CONSTRAINT fk_design_file_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE,

    -- ONEMEP-39 asks the application to steer a repeat filename towards "upload a
    -- new version" rather than creating a duplicate top-level row. The exact
    -- matching rule is flagged in that ticket as needing confirmation; normalised
    -- filename is the assumption, enforced here so it cannot be bypassed.
    CONSTRAINT uq_design_file_name UNIQUE (design_id, display_name_normalized)
);

CREATE INDEX idx_design_file_design ON design_file (design_id);

-- ── Versions ────────────────────────────────────────────────────────────────
-- Append-only. A new upload adds a row; it never updates an existing one, which
-- is what makes "previous versions shall not be overwritten" true by
-- construction rather than by convention.
CREATE TABLE design_file_version (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id            BIGINT        NOT NULL,

    revision_no        INT           NOT NULL,
    revision_label     VARCHAR(10)   NOT NULL,

    -- Opaque object-store path. Never derived from the uploaded filename.
    storage_key        VARCHAR(1024) NOT NULL,

    original_filename  VARCHAR(255)  NOT NULL,
    file_extension     VARCHAR(20),
    content_type       VARCHAR(150),
    size_bytes         BIGINT        NOT NULL,

    -- Optional note from the upload dialog; applies to every file in that batch.
    note               VARCHAR(1000),

    created_date       TIMESTAMP     NOT NULL,
    created_by         BIGINT,
    updated_by         BIGINT,
    updated_date       TIMESTAMP,

    CONSTRAINT fk_design_file_version_file FOREIGN KEY (file_id)
        REFERENCES design_file (id) ON DELETE CASCADE,

    -- The backstop behind the row-lock allocator: even if two writers raced past
    -- it, the database refuses to store R3 twice for one file.
    CONSTRAINT uq_design_file_revision UNIQUE (file_id, revision_no),

    CONSTRAINT ck_design_file_size CHECK (size_bytes > 0)
);

CREATE INDEX idx_design_file_version_file ON design_file_version (file_id, revision_no DESC);

ALTER TABLE design_file
    ADD CONSTRAINT fk_design_file_current_version FOREIGN KEY (current_version_id)
        REFERENCES design_file_version (id);

-- ── Comments ────────────────────────────────────────────────────────────────
-- Bound to a *version*, never to the logical file. ONEMEP-39: "A comment shall
-- never lose its version association when a newer file version is uploaded."
--
-- No ON DELETE CASCADE from the version: a version carrying comments must not be
-- deletable at all, so a cascade here would quietly destroy the very history the
-- deletion rules exist to protect.
CREATE TABLE design_file_comment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id    BIGINT        NOT NULL,
    body          VARCHAR(2000) NOT NULL,

    -- Open comments block final approval (ONEMEP-40); resolved ones stay visible.
    status        VARCHAR(10)   NOT NULL DEFAULT 'OPEN',

    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_design_file_comment_version FOREIGN KEY (version_id)
        REFERENCES design_file_version (id),
    CONSTRAINT ck_design_file_comment_status CHECK (status IN ('OPEN', 'CLOSED'))
);

CREATE INDEX idx_design_file_comment_version ON design_file_comment (version_id);
