-- ============================================================================
-- V22 - File approval flow (ONEMEP-40).
--
-- Approval attaches to a *logical file*, but every request permanently records
-- the revision that was submitted. That pairing is the whole design: the
-- Approvals table shows one row per file, and expanding it shows a version-
-- correct journey underneath.
--
-- Three rules are enforced by the schema rather than only by the service,
-- because each is a race the service alone would lose:
--   * at most one PENDING request per file;
--   * a revision may complete at most one approval cycle;
--   * a request's submitted revision can never be rewritten.
-- ============================================================================

-- ── Who is "the Principal" ──────────────────────────────────────────────────
-- ONEMEP-40 routes to a Principal but never defines one. Resolved here as a
-- role: a team role is marked principal, and a Project's Principal is whichever
-- of its members holds that role. That keeps it per-project and data-driven —
-- no user id is ever hardcoded, and reassigning the role moves the Principal.
ALTER TABLE team_role_master ADD COLUMN is_principal BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE approval_request (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id           BIGINT      NOT NULL,
    file_id             BIGINT      NOT NULL,

    -- Frozen at submission. Uploading R3 later must not drag an R2 request onto it.
    version_id          BIGINT      NOT NULL,

    requester_id        BIGINT      NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    -- Which stage is currently outstanding.
    current_stage       VARCHAR(20) NOT NULL DEFAULT 'INITIAL',
    route_to_principal  BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Set when the previous request for this file ended in EDIT_REQUESTED.
    is_resubmission     BOOLEAN     NOT NULL DEFAULT FALSE,

    completed_at        TIMESTAMP,

    -- Guards the recall-versus-decide race ONEMEP-40 describes: "the first
    -- successfully committed workflow change shall take precedence".
    version             INT         NOT NULL DEFAULT 0,

    created_date        TIMESTAMP   NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    updated_date        TIMESTAMP,

    CONSTRAINT fk_approval_design  FOREIGN KEY (design_id)  REFERENCES design (id) ON DELETE CASCADE,
    -- Approval rows are approvals *of this file*, so they go when it does. The enduring
    -- record ONEMEP-39 asks for lives in design_activity_log, which holds the events as prose
    -- and therefore survives whatever it describes.
    CONSTRAINT fk_approval_file    FOREIGN KEY (file_id)
        REFERENCES design_file (id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_version FOREIGN KEY (version_id)
        REFERENCES design_file_version (id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_requester FOREIGN KEY (requester_id) REFERENCES user_master (id),

    CONSTRAINT ck_approval_status CHECK (status IN
        ('PENDING', 'APPROVED', 'EDIT_REQUESTED', 'REJECTED', 'RECALLED', 'CANCELLED')),
    CONSTRAINT ck_approval_stage CHECK (current_stage IN ('INITIAL', 'PRINCIPAL'))
);

-- "Only one active Approval Request shall exist for a logical file at a time."
-- A service check alone loses to two simultaneous submissions.
CREATE UNIQUE INDEX uq_approval_pending_per_file
    ON approval_request (file_id) WHERE status = 'PENDING';

-- "The same Revision shall not be submitted again after a completed decision."
-- RECALLED and CANCELLED are absent deliberately: neither is a decision on the
-- file, so the same revision may legitimately be sent again after one.
CREATE UNIQUE INDEX uq_approval_completed_per_version
    ON approval_request (version_id)
    WHERE status IN ('APPROVED', 'EDIT_REQUESTED', 'REJECTED');

CREATE INDEX idx_approval_design    ON approval_request (design_id);
CREATE INDEX idx_approval_file      ON approval_request (file_id, id DESC);
CREATE INDEX idx_approval_requester ON approval_request (requester_id, status);

-- ── Assignees ───────────────────────────────────────────────────────────────
-- One row per approver per stage. Completion is computed from these rows rather
-- than tracked as a counter, so "1 of 3 approved" can never drift from reality.
CREATE TABLE approval_assignee (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id   BIGINT      NOT NULL,
    user_id      BIGINT      NOT NULL,
    stage        VARCHAR(20) NOT NULL,
    decision     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    decided_at   TIMESTAMP,
    note         VARCHAR(1000),

    -- An admin reassignment retires the old row rather than editing it, so the
    -- journey still shows who was originally asked.
    is_active    BOOLEAN     NOT NULL DEFAULT TRUE,

    created_date TIMESTAMP   NOT NULL,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP,

    CONSTRAINT fk_approval_assignee_request FOREIGN KEY (request_id)
        REFERENCES approval_request (id) ON DELETE CASCADE,
    CONSTRAINT fk_approval_assignee_user FOREIGN KEY (user_id) REFERENCES user_master (id),

    CONSTRAINT ck_approval_assignee_stage CHECK (stage IN ('INITIAL', 'PRINCIPAL')),
    CONSTRAINT ck_approval_assignee_decision CHECK (decision IN
        ('PENDING', 'APPROVED', 'EDIT_REQUESTED', 'REJECTED'))
);

-- One live assignment per person per stage; retired rows are exempt so a
-- reassignment can hand the task back to someone who previously held it.
CREATE UNIQUE INDEX uq_approval_assignee_active
    ON approval_assignee (request_id, user_id, stage) WHERE is_active;

CREATE INDEX idx_approval_assignee_request ON approval_assignee (request_id);
CREATE INDEX idx_approval_assignee_user    ON approval_assignee (user_id, decision);

-- ── Checklist snapshot ──────────────────────────────────────────────────────
-- A literal copy of what the requester ticked, never a reference to the master.
-- ONEMEP-40: editing, deactivating or deleting the Checklist Master afterwards
-- must not alter a historic request — which only holds if nothing points back.
CREATE TABLE approval_checklist_snapshot (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     BIGINT       NOT NULL,
    checklist_name VARCHAR(50),
    item_text      VARCHAR(250) NOT NULL,
    checked        BOOLEAN      NOT NULL,
    sort_order     INT          NOT NULL,
    created_date   TIMESTAMP    NOT NULL,
    created_by     BIGINT,
    updated_by     BIGINT,
    updated_date   TIMESTAMP,

    CONSTRAINT fk_approval_snapshot_request FOREIGN KEY (request_id)
        REFERENCES approval_request (id) ON DELETE CASCADE
);

CREATE INDEX idx_approval_snapshot_request ON approval_checklist_snapshot (request_id, sort_order);

-- ── Note history ────────────────────────────────────────────────────────────
-- Append-only record of every lifecycle event, with the acting user and the
-- revision it applied to. Never updated.
CREATE TABLE approval_note (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id     BIGINT       NOT NULL,
    action         VARCHAR(30)  NOT NULL,
    note           VARCHAR(1000),
    revision_label VARCHAR(10),
    created_date   TIMESTAMP    NOT NULL,
    created_by     BIGINT,
    updated_by     BIGINT,
    updated_date   TIMESTAMP,

    CONSTRAINT fk_approval_note_request FOREIGN KEY (request_id)
        REFERENCES approval_request (id) ON DELETE CASCADE,
    CONSTRAINT ck_approval_note_action CHECK (action IN
        ('RAISED', 'APPROVED', 'EDIT_REQUESTED', 'REJECTED', 'RECALLED',
         'REASSIGNED', 'CANCELLED', 'ROUTED_TO_PRINCIPAL'))
);

CREATE INDEX idx_approval_note_request ON approval_note (request_id, id DESC);
