-- ============================================================================
-- V23 - Design discussion thread (ONEMEP-41) and time tracking (ONEMEP-42).
--
-- Two independent features sharing one migration because neither depends on the
-- other and both hang directly off design.
--
-- ONEMEP-41 is emphatic that a Discussion message is NOT a File Comment and NOT
-- an Approval Note. All three exist, and this is the third: general Design-level
-- conversation, with no workflow meaning whatsoever.
-- ============================================================================

CREATE TABLE design_message (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id     BIGINT        NOT NULL,
    body          VARCHAR(4000) NOT NULL,
    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_design_message_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE
);

CREATE INDEX idx_design_message_design ON design_message (design_id, id DESC);

-- One row per *distinct* user mentioned in a message. ONEMEP-41: mentioning the
-- same person twice in one message must still produce a single notification, so
-- the uniqueness is enforced here rather than left to the caller to remember.
CREATE TABLE design_message_mention (
    id            BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id    BIGINT    NOT NULL,
    user_id       BIGINT    NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_design_message_mention_message FOREIGN KEY (message_id)
        REFERENCES design_message (id) ON DELETE CASCADE,
    CONSTRAINT fk_design_message_mention_user FOREIGN KEY (user_id)
        REFERENCES user_master (id),
    CONSTRAINT uq_design_message_mention UNIQUE (message_id, user_id)
);

CREATE INDEX idx_design_message_mention_user ON design_message_mention (user_id);

-- ── Notifications ───────────────────────────────────────────────────────────
-- Introduced for @mentions, but deliberately generic: ONEMEP-40 also requires
-- approvers to be notified, and that can reuse this rather than growing a second
-- mechanism. Delivery is in-app only; email remains the separate concern the
-- notification package already handles.
CREATE TABLE user_notification (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT        NOT NULL,
    type          VARCHAR(40)   NOT NULL,

    -- Denormalised prose, so a notification still reads correctly after whatever
    -- it describes has changed or gone.
    title         VARCHAR(200)  NOT NULL,
    body          VARCHAR(1000),

    -- Enough to navigate back to the source; nullable so unrelated types can omit it.
    design_id     BIGINT,
    is_read       BOOLEAN       NOT NULL DEFAULT FALSE,
    read_at       TIMESTAMP,

    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_user_notification_user FOREIGN KEY (user_id) REFERENCES user_master (id),
    CONSTRAINT fk_user_notification_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE,
    CONSTRAINT ck_user_notification_type CHECK (type IN ('DISCUSSION_MENTION'))
);

CREATE INDEX idx_user_notification_user ON user_notification (user_id, is_read, id DESC);

-- ── Time tracking ───────────────────────────────────────────────────────────
-- work_date is a DATE and logged_at an instant, deliberately. ONEMEP-42 returns
-- to this repeatedly: "Logged 7 h on 6 Aug" recorded on 8 Aug must show both
-- dates, so they can never collapse into one column.
--
-- Entries are never consolidated. Two logs on the same day stay two rows, each
-- keeping its own note and its own logged timestamp.
CREATE TABLE design_time_entry (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    design_id     BIGINT        NOT NULL,
    user_id       BIGINT        NOT NULL,

    work_date     DATE          NOT NULL,
    hours         NUMERIC(4, 2) NOT NULL,
    note          VARCHAR(500),

    -- System-generated and never editable.
    logged_at     TIMESTAMP     NOT NULL,

    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,

    CONSTRAINT fk_design_time_entry_design FOREIGN KEY (design_id)
        REFERENCES design (id) ON DELETE CASCADE,
    CONSTRAINT fk_design_time_entry_user FOREIGN KEY (user_id) REFERENCES user_master (id),

    -- A single entry cannot exceed a day. The 24-hour *daily total* spans rows and
    -- is therefore checked in the service, against the latest committed total.
    CONSTRAINT ck_design_time_hours CHECK (hours > 0 AND hours <= 24)
);

CREATE INDEX idx_design_time_entry_design ON design_time_entry (design_id, work_date DESC);
CREATE INDEX idx_design_time_entry_user   ON design_time_entry (design_id, user_id, work_date);
