-- ============================================================================
-- V25 - Bulk Design import (ONEMEP-35, import half).
--
-- Three tables for one job: the batch the user submitted, each spreadsheet in
-- it, and the per-row problems that stopped individual rows importing.
--
-- Why any of this is persisted at all: the import is asynchronous. POST returns
-- 202 with a batch id and the work continues on a background thread, so the
-- progress the ticket describes ("Ready / Uploading / Processing / Imported /
-- Completed with errors / Failed", per file) has to live somewhere a later GET
-- can read. In-memory state would not survive a restart mid-import and would be
-- invisible to a second instance behind the gateway.
--
-- Partial success is the required behaviour, which is why rows and files carry
-- independent counters: a file is 'COMPLETED_WITH_ERRORS' when some of its rows
-- imported and some did not, and the batch is likewise the aggregate of its
-- files rather than an all-or-nothing flag.
-- ============================================================================

CREATE TABLE design_import_batch (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id     BIGINT       NOT NULL,

    status         VARCHAR(30)  NOT NULL DEFAULT 'READY',

    total_files    INT          NOT NULL DEFAULT 0,
    total_rows     INT          NOT NULL DEFAULT 0,
    imported_rows  INT          NOT NULL DEFAULT 0,
    failed_rows    INT          NOT NULL DEFAULT 0,

    -- Free prose for the whole batch, e.g. the ticket's
    -- "42 of 50 Designs imported. 8 rows require correction."
    summary        VARCHAR(500),

    started_at     TIMESTAMP,
    finished_at    TIMESTAMP,

    created_date   TIMESTAMP    NOT NULL,
    created_by     BIGINT,
    updated_by     BIGINT,
    updated_date   TIMESTAMP,

    CONSTRAINT fk_design_import_batch_project FOREIGN KEY (project_id)
        REFERENCES project_master (id) ON DELETE CASCADE,

    CONSTRAINT ck_design_import_batch_status CHECK (status IN
        ('READY', 'UPLOADING', 'PROCESSING', 'IMPORTED', 'COMPLETED_WITH_ERRORS', 'FAILED'))
);

CREATE INDEX idx_design_import_batch_project ON design_import_batch (project_id, created_date DESC);

-- ── One uploaded spreadsheet ────────────────────────────────────────────────
-- storage_key is nullable for the window between inserting the row (READY) and
-- the bytes actually landing in object storage (UPLOADING -> stored). Bytes are
-- never written inside a transaction, so that window genuinely exists — see
-- DesignFileServiceImpl for the same allocate/store/persist split.
CREATE TABLE design_import_file (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id           BIGINT       NOT NULL,

    -- Position in the submitted batch; the status list is shown in upload order.
    ordinal            INT          NOT NULL,

    original_filename  VARCHAR(255) NOT NULL,
    file_extension     VARCHAR(10)  NOT NULL,
    content_type       VARCHAR(150),
    size_bytes         BIGINT       NOT NULL DEFAULT 0,
    storage_key        VARCHAR(1024),

    status             VARCHAR(30)  NOT NULL DEFAULT 'READY',

    total_rows         INT          NOT NULL DEFAULT 0,
    imported_rows      INT          NOT NULL DEFAULT 0,
    failed_rows        INT          NOT NULL DEFAULT 0,

    -- File-level outcome: why a whole file failed (unreadable, missing header),
    -- or the per-file equivalent of the batch summary.
    message            VARCHAR(500),

    -- Set when failed_rows exceeded the retained-error cap, so the UI can say the
    -- list is not the whole story rather than quietly showing a short one.
    errors_truncated   BOOLEAN      NOT NULL DEFAULT FALSE,

    created_date       TIMESTAMP    NOT NULL,
    created_by         BIGINT,
    updated_by         BIGINT,
    updated_date       TIMESTAMP,

    CONSTRAINT fk_design_import_file_batch FOREIGN KEY (batch_id)
        REFERENCES design_import_batch (id) ON DELETE CASCADE,

    CONSTRAINT ck_design_import_file_status CHECK (status IN
        ('READY', 'UPLOADING', 'PROCESSING', 'IMPORTED', 'COMPLETED_WITH_ERRORS', 'FAILED')),

    CONSTRAINT uq_design_import_file_ordinal UNIQUE (batch_id, ordinal)
);

CREATE INDEX idx_design_import_file_batch ON design_import_file (batch_id, ordinal);

-- ── Per-row validation errors ───────────────────────────────────────────────
-- row_number is the number the user sees in Excel — the header is row 1 — so an
-- error reads "Row 14" against the row they can actually go and look at.
--
-- One row can fail more than one rule at once (a duplicate Design Number AND a
-- duplicate Title are two separate rules, never a composite one), so this is a
-- list per row rather than a single message column on a row record.
CREATE TABLE design_import_row_error (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id      BIGINT        NOT NULL,

    row_number   INT           NOT NULL,

    -- Which column the problem is in; NULL for whole-row rules such as the
    -- duplicate checks, which belong to no single column.
    column_name  VARCHAR(60),

    message      VARCHAR(500)  NOT NULL,

    created_date TIMESTAMP     NOT NULL,
    created_by   BIGINT,
    updated_by   BIGINT,
    updated_date TIMESTAMP,

    CONSTRAINT fk_design_import_row_error_file FOREIGN KEY (file_id)
        REFERENCES design_import_file (id) ON DELETE CASCADE
);

CREATE INDEX idx_design_import_row_error_file ON design_import_row_error (file_id, row_number, id);
