-- ============================================================================
-- V26 - The full reference-data catalogue, as confirmed by the business.
--
-- V16 seeded only the codes that appeared in the Sprint 3 acceptance criteria,
-- and said so at the time: "PROVISIONAL ... Extend via a follow-up migration
-- once the business confirms; do not edit this file after it has been applied."
-- This is that follow-up. V16 and V18 are untouched, so no checksum changes.
--
--     DISCIPLINE    3 -> 10
--     DESIGN_TYPE   2 -> 17
--     SUBJECT       1 -> 19
--     FLOOR         2 -> 15 active
--     STAGE         6 ->  9 active
--
-- Written as an UPSERT on uq_lookup_type_code, so this is declarative rather
-- than incremental: it states what the catalogue should contain, updates the
-- rows V16 already created instead of duplicating them, and re-running it is a
-- no-op. Verified by applying it twice over a V1-V25 database: zero duplicate
-- (lookup_type, code) pairs, no error on the second run.
--
-- sort_order follows the order the business supplied, because that is the order
-- the dropdowns should render in.
--
-- NOT HERE, and deliberately:
--   * "Any / Applies to all" is not a catalogue row. ChecklistDto.AppliesTo
--     already treats an EMPTY list as Any; seeding an ANY row would create a
--     second, conflicting way to say the same thing.
--   * Sheet size (A0-A4) is a free-text column, not a catalogue. Making it one
--     needs LookupType and ck_lookup_type changed, which is a code change.
--   * Work progress is a Java enum plus ck_design_work_progress. The confirmed
--     list adds three states and drops COMPLETED, so it needs its own migration
--     and a decision about existing COMPLETED rows.
-- ============================================================================

INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date, created_by)
VALUES
    ('DISCIPLINE', 'M', 'Mechanical / HVAC', 1, TRUE, NOW(), 1),
    ('DISCIPLINE', 'E', 'Electrical', 2, TRUE, NOW(), 1),
    ('DISCIPLINE', 'ELV', 'ELV / low-voltage', 3, TRUE, NOW(), 1),
    ('DISCIPLINE', 'SS', 'Security systems', 4, TRUE, NOW(), 1),
    ('DISCIPLINE', 'PHE', 'Public health / plumbing', 5, TRUE, NOW(), 1),
    ('DISCIPLINE', 'FF', 'Fire fighting', 6, TRUE, NOW(), 1),
    ('DISCIPLINE', 'GD', 'General', 7, TRUE, NOW(), 1),
    ('DISCIPLINE', 'AUD', 'Audio-visual', 8, TRUE, NOW(), 1),
    ('DISCIPLINE', 'CO', 'Coordination', 9, TRUE, NOW(), 1),
    ('DISCIPLINE', 'MEP', 'MEP combined', 10, TRUE, NOW(), 1)
ON CONFLICT (lookup_type, code) DO UPDATE
    SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order,
        is_active = TRUE, updated_date = NOW(), updated_by = 1;

INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date, created_by)
VALUES
    ('DESIGN_TYPE', 'PLN', 'Plan / layout', 1, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'SCH', 'Schematic', 2, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'RSR', 'Riser diagram', 3, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'DTL', 'Detail', 4, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'SEC', 'Section', 5, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'SLP', 'Sleeves & penetrations', 6, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'BOQ', 'Bill of quantities', 7, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'CAL', 'Calculation', 8, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'DBR', 'Design basis report', 9, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'TD', 'Technical datasheet', 10, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'PID', 'P&ID', 11, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'CWD', 'Coordinated working drawing', 12, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'MST', 'Method statement', 13, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'SHF', 'Shaft drawing', 14, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'LSH', 'Load schedule', 15, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'GDS', 'General design sheet', 16, TRUE, NOW(), 1),
    ('DESIGN_TYPE', 'TQS', 'Technical query sheet', 17, TRUE, NOW(), 1)
ON CONFLICT (lookup_type, code) DO UPDATE
    SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order,
        is_active = TRUE, updated_date = NOW(), updated_by = 1;

INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date, created_by)
VALUES
    ('SUBJECT', 'GEN', 'General', 1, TRUE, NOW(), 1),
    ('SUBJECT', 'LAYOUT', 'Layout', 2, TRUE, NOW(), 1),
    ('SUBJECT', 'PLAN', 'Plan', 3, TRUE, NOW(), 1),
    ('SUBJECT', 'CHW', 'Chilled water', 4, TRUE, NOW(), 1),
    ('SUBJECT', 'HW', 'Hot water', 5, TRUE, NOW(), 1),
    ('SUBJECT', 'VENT', 'Ventilation', 6, TRUE, NOW(), 1),
    ('SUBJECT', 'DUCT', 'Ducting', 7, TRUE, NOW(), 1),
    ('SUBJECT', 'LTG', 'Lighting', 8, TRUE, NOW(), 1),
    ('SUBJECT', 'PWR', 'Power', 9, TRUE, NOW(), 1),
    ('SUBJECT', 'LV', 'Low voltage', 10, TRUE, NOW(), 1),
    ('SUBJECT', 'HT', 'HT power', 11, TRUE, NOW(), 1),
    ('SUBJECT', 'SLD', 'Single line diagram', 12, TRUE, NOW(), 1),
    ('SUBJECT', 'DBR', 'Design basis', 13, TRUE, NOW(), 1),
    ('SUBJECT', 'HYD', 'Hydrant', 14, TRUE, NOW(), 1),
    ('SUBJECT', 'WS', 'Water supply', 15, TRUE, NOW(), 1),
    ('SUBJECT', 'DR', 'Drainage', 16, TRUE, NOW(), 1),
    ('SUBJECT', 'STP', 'STP', 17, TRUE, NOW(), 1),
    ('SUBJECT', 'FA', 'Fire alarm', 18, TRUE, NOW(), 1),
    ('SUBJECT', 'SPR', 'Sprinkler', 19, TRUE, NOW(), 1)
ON CONFLICT (lookup_type, code) DO UPDATE
    SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order,
        is_active = TRUE, updated_date = NOW(), updated_by = 1;

-- 'XX' is here because the confirmed list asks for it, but note the clash:
-- DesignNumberGenerator emits XX as the placeholder for an omitted segment, so
-- a Design whose Floor is genuinely XX and one whose Floor was left blank
-- generate identical Design Numbers. Worth confirming that is intended.
INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date, created_by)
VALUES
    ('FLOOR', 'XX', 'Not applicable', 1, TRUE, NOW(), 1),
    ('FLOOR', 'B2', 'Basement 2', 2, TRUE, NOW(), 1),
    ('FLOOR', 'B1', 'Basement 1', 3, TRUE, NOW(), 1),
    ('FLOOR', '00', 'Ground floor', 4, TRUE, NOW(), 1),
    ('FLOOR', '01', 'Level 01', 5, TRUE, NOW(), 1),
    ('FLOOR', '02', 'Level 02', 6, TRUE, NOW(), 1),
    ('FLOOR', '03', 'Level 03', 7, TRUE, NOW(), 1),
    ('FLOOR', '04', 'Level 04', 8, TRUE, NOW(), 1),
    ('FLOOR', '05', 'Level 05', 9, TRUE, NOW(), 1),
    ('FLOOR', '06', 'Level 06', 10, TRUE, NOW(), 1),
    ('FLOOR', '07', 'Level 07', 11, TRUE, NOW(), 1),
    ('FLOOR', '08', 'Level 08', 12, TRUE, NOW(), 1),
    ('FLOOR', '09', 'Level 09', 13, TRUE, NOW(), 1),
    ('FLOOR', '10', 'Level 10', 14, TRUE, NOW(), 1),
    ('FLOOR', 'RF', 'Roof', 15, TRUE, NOW(), 1)
ON CONFLICT (lookup_type, code) DO UPDATE
    SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order,
        is_active = TRUE, updated_date = NOW(), updated_by = 1;

INSERT INTO lookup_value (lookup_type, code, label, sort_order, is_active, created_date, created_by)
VALUES
    ('STAGE', 'SD', 'Schematic design', 1, TRUE, NOW(), 1),
    ('STAGE', 'DD', 'Detailed design', 2, TRUE, NOW(), 1),
    ('STAGE', 'IFA', 'Issued for approval', 3, TRUE, NOW(), 1),
    ('STAGE', 'IFR', 'Issued for review', 4, TRUE, NOW(), 1),
    ('STAGE', 'IFI', 'Issued for information', 5, TRUE, NOW(), 1),
    ('STAGE', 'TS', 'Tender set', 6, TRUE, NOW(), 1),
    ('STAGE', 'GFC-C', 'Good for construction (cond)', 7, TRUE, NOW(), 1),
    ('STAGE', 'GFC', 'Good for construction', 8, TRUE, NOW(), 1),
    ('STAGE', 'AB', 'As built', 9, TRUE, NOW(), 1)
ON CONFLICT (lookup_type, code) DO UPDATE
    SET label = EXCLUDED.label, sort_order = EXCLUDED.sort_order,
        is_active = TRUE, updated_date = NOW(), updated_by = 1;

-- ── Retire the codes the confirmed list drops ───────────────────────────────
-- Deactivated rather than deleted. Existing Designs reference these by FK and
-- embed the code in their Design Number, so a delete would either violate the
-- constraint or orphan history. Inactive means "cannot be chosen from now on",
-- which is the actual intent, and it reverses with a single UPDATE.
--
--   STAGE 'CON' (Concept) - came from the V14 comment, absent from the list
--   FLOOR 'L01'           - superseded by '01'
UPDATE lookup_value SET is_active = FALSE, updated_date = NOW(), updated_by = 1
WHERE (lookup_type = 'STAGE' AND code = 'CON')
   OR (lookup_type = 'FLOOR' AND code = 'L01');
