-- ============================================================================
-- V2 - PROJECT epic expansion (Jira ONEMEP-12/13/14/15)
--
-- Brings the Project domain in line with the story acceptance criteria:
--   * New configured-list master data: Handling Office, Detailing Level.
--   * Category gains a numeric series_code used for confirmed Project IDs.
--   * project_master gains Type (Confirmed / Non-confirmed), Client, Location,
--     Handling Office, Detailing Level and a type_locked guard.
--   * A per-project activity audit log.
--   * Lifecycle set extended with CLOSED (On Hold / Closed require a reason).
-- ============================================================================

-- ── Master Data: Handling Office (configured list for projects) ─────────────
CREATE TABLE handling_office_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_handling_office_name UNIQUE (name)
);

-- ── Master Data: Detailing Level (configured list for projects) ─────────────
CREATE TABLE detailing_level_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150) NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT uq_detailing_level_name UNIQUE (name)
);

-- ── Category: numeric series code drives confirmed Project IDs (e.g. 4 -> 40012)
ALTER TABLE category_master ADD COLUMN series_code INTEGER;
ALTER TABLE category_master ADD CONSTRAINT uq_category_series_code UNIQUE (series_code);

-- ── Project: new business fields from ONEMEP-13/14 ──────────────────────────
ALTER TABLE project_master ADD COLUMN project_type      VARCHAR(20)  NOT NULL DEFAULT 'NON_CONFIRMED';
ALTER TABLE project_master ADD COLUMN type_locked       BOOLEAN      NOT NULL DEFAULT FALSE;
ALTER TABLE project_master ADD COLUMN client            VARCHAR(50);
ALTER TABLE project_master ADD COLUMN location          VARCHAR(50);
ALTER TABLE project_master ADD COLUMN handling_office_id BIGINT;
ALTER TABLE project_master ADD COLUMN detailing_level_id BIGINT;

ALTER TABLE project_master
    ADD CONSTRAINT fk_project_handling_office
        FOREIGN KEY (handling_office_id) REFERENCES handling_office_master (id);
ALTER TABLE project_master
    ADD CONSTRAINT fk_project_detailing_level
        FOREIGN KEY (detailing_level_id) REFERENCES detailing_level_master (id);
ALTER TABLE project_master
    ADD CONSTRAINT ck_project_type CHECK (project_type IN ('CONFIRMED', 'NON_CONFIRMED'));

CREATE INDEX idx_project_handling_office ON project_master (handling_office_id);
CREATE INDEX idx_project_detailing_level ON project_master (detailing_level_id);

-- Extend the lifecycle domain with CLOSED (On Hold / Closed require a change reason).
ALTER TABLE project_master DROP CONSTRAINT ck_project_lifecycle;
ALTER TABLE project_master ADD CONSTRAINT ck_project_lifecycle CHECK (lifecycle_status IN
    ('DRAFT', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CLOSED', 'CANCELLED', 'ARCHIVED'));

-- ── Project Activity Log (ONEMEP-15 audit trail) ────────────────────────────
-- Append-only per-project event log. created_by/created_date carry the actor and
-- timestamp; action is a stable code, detail is human-readable, reason is optional.
CREATE TABLE project_activity_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT        NOT NULL,
    action        VARCHAR(50)   NOT NULL,
    detail        VARCHAR(1000),
    reason        VARCHAR(500),
    created_date  TIMESTAMP     NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT fk_project_activity_project FOREIGN KEY (project_id) REFERENCES project_master (id)
);
CREATE INDEX idx_project_activity_project ON project_activity_log (project_id);
