-- ============================================================================
-- V3 - Project Overview sections (Jira ONEMEP-15)
--
-- Adds the three read-only-on-overview sub-resources hung off a project:
--   * project_spec_sheet       — uploaded specs sheets (.doc/.docx/.pdf, <=150MB)
--   * project_delivery_schedule— delivery milestones / deliverables
--   * project_stakeholder      — stakeholder directory (project head, architect, ...)
-- ============================================================================

-- ── Specs sheet attachments ─────────────────────────────────────────────────
-- File bytes are stored in-row as BYTEA (TOAST-backed). Metadata is queried without
-- loading the bytes so listings stay cheap.
CREATE TABLE project_spec_sheet (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(150),
    file_extension VARCHAR(10) NOT NULL,
    file_size     BIGINT       NOT NULL,
    file_data     BYTEA        NOT NULL,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT fk_spec_sheet_project FOREIGN KEY (project_id) REFERENCES project_master (id),
    CONSTRAINT ck_spec_sheet_extension CHECK (LOWER(file_extension) IN ('doc', 'docx', 'pdf'))
);
CREATE INDEX idx_spec_sheet_project ON project_spec_sheet (project_id);

-- ── Delivery schedule ───────────────────────────────────────────────────────
CREATE TABLE project_delivery_schedule (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    milestone     VARCHAR(200) NOT NULL,
    deliverable   VARCHAR(500),
    planned_date  DATE,
    actual_date   DATE,
    status        VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    remarks       VARCHAR(1000),
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT fk_delivery_project FOREIGN KEY (project_id) REFERENCES project_master (id),
    CONSTRAINT ck_delivery_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'DELAYED'))
);
CREATE INDEX idx_delivery_project ON project_delivery_schedule (project_id);

-- ── Stakeholder directory ───────────────────────────────────────────────────
-- role covers Project Head / Architect / Structure and other common project roles.
CREATE TABLE project_stakeholder (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    role          VARCHAR(30)  NOT NULL,
    name          VARCHAR(150) NOT NULL,
    organization  VARCHAR(150),
    email         VARCHAR(150),
    phone         VARCHAR(50),
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT fk_stakeholder_project FOREIGN KEY (project_id) REFERENCES project_master (id),
    CONSTRAINT ck_stakeholder_role CHECK (role IN
        ('PROJECT_HEAD', 'ARCHITECT', 'STRUCTURE', 'CLIENT', 'CONSULTANT', 'CONTRACTOR', 'OTHER'))
);
CREATE INDEX idx_stakeholder_project ON project_stakeholder (project_id);
