-- ============================================================================
-- V4 - Project Technical Master (Jira ONEMEP-29)
--
-- A consolidated, project-scoped Technical Master form. One record per project
-- (uq_technical_master_project) captures:
--   * project technical inputs        — general fields on project_technical_master
--   * common / category-specific params— project_technical_parameter (scope column)
--   * DID specifications              — project_did_specification
--   * attachments                     — project_technical_attachment (BYTEA, like spec sheets)
--
-- Delivery schedule and client information are NOT stored here: they are surfaced
-- read-only from the existing project_delivery_schedule table and
-- project_master.client/location (single source of truth).
--
-- Business/history versioning is deferred (ONEMEP-30). The `version` column is an
-- optimistic-lock counter only; it also leaves a forward-compat seam for ONEMEP-30.
-- The existing global `technical_master` catalog (ONEMEP-29 provisional) is unchanged;
-- parameters reference it via technical_field_id.
-- ============================================================================

-- ── Aggregate root: one Technical Master per project ────────────────────────
CREATE TABLE project_technical_master (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id    BIGINT       NOT NULL,
    remarks       VARCHAR(2000),
    version       BIGINT       NOT NULL DEFAULT 0,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_date  TIMESTAMP    NOT NULL,
    created_by    BIGINT,
    updated_by    BIGINT,
    updated_date  TIMESTAMP,
    CONSTRAINT fk_tech_master_project FOREIGN KEY (project_id) REFERENCES project_master (id),
    CONSTRAINT uq_tech_master_project UNIQUE (project_id)
);

-- ── Common + category-specific technical parameters ─────────────────────────
-- Each row references a catalog technical field (technical_master) and an optional unit,
-- and carries the captured value. `scope` separates common vs category-specific inputs.
CREATE TABLE project_technical_parameter (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id BIGINT       NOT NULL,
    scope               VARCHAR(20)  NOT NULL,
    technical_field_id  BIGINT       NOT NULL,
    unit_id             BIGINT,
    param_value         VARCHAR(500),
    remarks             VARCHAR(1000),
    created_date        TIMESTAMP    NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_tech_param_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT fk_tech_param_field FOREIGN KEY (technical_field_id)
        REFERENCES technical_master (id),
    CONSTRAINT fk_tech_param_unit FOREIGN KEY (unit_id) REFERENCES unit_master (id),
    CONSTRAINT ck_tech_param_scope CHECK (scope IN ('COMMON', 'CATEGORY_SPECIFIC')),
    CONSTRAINT uq_tech_param UNIQUE (technical_master_id, scope, technical_field_id)
);
CREATE INDEX idx_tech_param_master ON project_technical_parameter (technical_master_id);

-- ── DID specifications ──────────────────────────────────────────────────────
-- Repeatable line items. Exact field set is provisional (ONEMEP-29 has no schema);
-- modeled as name + specification value + optional unit + remarks.
CREATE TABLE project_did_specification (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id BIGINT       NOT NULL,
    name                VARCHAR(200) NOT NULL,
    specification       VARCHAR(500),
    unit_id             BIGINT,
    remarks             VARCHAR(1000),
    created_date        TIMESTAMP    NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_did_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT fk_did_unit FOREIGN KEY (unit_id) REFERENCES unit_master (id)
);
CREATE INDEX idx_did_master ON project_did_specification (technical_master_id);

-- ── Attachments ─────────────────────────────────────────────────────────────
-- Mirrors project_spec_sheet: bytes stored in-row as BYTEA, metadata queried without
-- loading the bytes. Same allow-list as spec sheets (.doc/.docx/.pdf, <=150MB).
CREATE TABLE project_technical_attachment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technical_master_id BIGINT       NOT NULL,
    file_name           VARCHAR(255) NOT NULL,
    content_type        VARCHAR(150),
    file_extension      VARCHAR(10)  NOT NULL,
    file_size           BIGINT       NOT NULL,
    file_data           BYTEA        NOT NULL,
    created_date        TIMESTAMP    NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    updated_date        TIMESTAMP,
    CONSTRAINT fk_tech_attachment_master FOREIGN KEY (technical_master_id)
        REFERENCES project_technical_master (id),
    CONSTRAINT ck_tech_attachment_extension CHECK (LOWER(file_extension) IN ('doc', 'docx', 'pdf'))
);
CREATE INDEX idx_tech_attachment_master ON project_technical_attachment (technical_master_id);
